const ADD_INITIAL_VALUE = 'ADD_INITIAL_VALUE'
const CHANGE_SPHERE_BOX = 'CHANGE_SPHERE_BOX'
const NAVIGATE_TO = 'NAVIGATE_TO'
const CHANGE_PATH = 'CHANGE_PATH'
const SET_SELECTED_CARD = 'SET_SELECTED_CARD'
const MAIL_ME_STATUS = 'MAIL_ME_STATUS'
const SHOW_MODAL = 'SHOW_MODAL'

export {
	ADD_INITIAL_VALUE,
	CHANGE_SPHERE_BOX,
	NAVIGATE_TO,
	CHANGE_PATH,
	SET_SELECTED_CARD,
	MAIL_ME_STATUS,
	SHOW_MODAL
}
