const ADD_INITIAL_VALUE = 'ADD_INITIAL_VALUE'
const CHANGE_GREEN_BOX = 'CHANGE_GREEN_BOX'
const NAVIGATE_TO = 'NAVIGATE_TO'
const CHANGE_PATH = 'CHANGE_PATH'
const SET_SELECTED_CARD = 'SET_SELECTED_CARD'

export {
	ADD_INITIAL_VALUE,
	CHANGE_GREEN_BOX,
	NAVIGATE_TO,
	CHANGE_PATH,
	SET_SELECTED_CARD
}
